#ifndef TSERVERTYPE_H
#define TSERVERTYPE_H

#define MAX_DATA_BUFFER_SIZE 40 //数据长度，不会超过40
// 包命令
enum command{
    CONNECTDOBOT = 0,
    DISCONNECTDOBOT,
    RESETDOBOT,
    PERIODICTACK,
    SETCMDTIMEOUT,

    SETENDTYPE,
    SETINITIALPOSE,
    GETPOSE,

    SETJOGSTATICPARAMS,
    SETJOGDYNAMICPARAMS,
    SETJOGINSTANTCMD,

    SETPLAYBACKSTATICPARAMS,
    SETPLAYBACKDYNAMICPARAMS,
    SETPLAYBACKBUFFERCMD,
};

struct package {
    int  cmd;
    char buf[MAX_DATA_BUFFER_SIZE]; // 数据对应DobotType.h中的结构体
};

#endif // TSERVERTYPE_H
